### ISSUE TITLE
request for resnet pretrained on kinetics400

### ISSUE THREAD

**Issue by dreamedrainbow** [xvjiarui/VFS#1]
Hi, thx for the great work and open source repository! 
Due to the poor computing resource, I can not train the resnet18 and resnet50 on kinetics400. Could you provide the pretrained model?

**Comment by xvjiarui** [comment]
Hi @dreamedrainbow 
Please find the pretrained models in [modelzoo](https://github.com/xvjiarui/VFS#model-zoo).

**Comment by dreamedrainbow** [comment]
@xvjiarui sorry, I am confused about the model in model zoo. Is [this model](https://github.com/xvjiarui/VFS/releases/download/v0.1-rc1/r18_nc_sgd_cos_100e_r2_1xNx8_k400-db1a4c0d.pth) a kinetics-pretrained model or a davis-train-saved model for fine-grained correspondence?

**Comment by xvjiarui** [comment]
Hi @dreamedrainbow 
We didn't fine-tune on DAVIS for fine-grained correspondence. We directly use the kinetics pretrained model to inference on DAVIS VOS.

**Comment by dreamedrainbow** [comment]
@xvjiarui thx, my problem solved.
