### ISSUE TITLE
Failed to reproduce the result (finally solved, due to bugs in dataset setup) 

### ISSUE THREAD

**Issue by JerryX1110** [xvjiarui/VFS#10]
Hi, I've tried to reproduce the result on DAVIS with ResNet18 backbone with the script as follows.

`./tools/dist_train.sh configs/r18_nc_sgd_cos_100e_r2_1xNx8_k400.py 2`

The official ckpt that you released is 66.73% J&F. However, for my retrained model, I got only ~60.86% J&F for the final checkpoint (epoch=100). The detailed evaluation result on DAVIS is as follows. So I am not sure what's going wrong. 

What's more, I would like to ask you about the deviation of results. Thanks.

Results copypaste  60.86
J&F-Mean: 0.6086
J-Mean: 0.5830
J-Recall: 0.6685
J-Decay: 0.2298
F-Mean: 0.6343
F-Recall: 0.7311
F-Decay: 0.2853

**Comment by xvjiarui** [comment]
Hi @JerryX1110 
The deviation of results is relatively small, with in 0.5 J&F mean. 
May I ask how large your Kinetics400 is?

**Comment by JerryX1110** [comment]
Oh, I think maybe something goes wrong with the dataset setup step. The video items that I downloaded with mmaction scripts are only ~30,000. Maybe using such less Kinetics400 is the reason for the drop in my reproduced performance. 

I previously also download kinetics400 with the other method and the video number is about ~240,000.

Thank you for your timely reply!

Best wishes for the New Year in 2022 👍

**Comment by gurdeepmaurya** [comment]
@JerryX1110 Were you able to reproduce the result?
