### ISSUE TITLE
Kinetics400 videos size and training times

### ISSUE THREAD

**Issue by paolomandica** [xvjiarui/VFS#12]
Hi, I'm trying to reproduce the training of the model using a ResNet-18 on two Quadro P6000 (24GB VRAM each) and the estimated duration of the training for 100 epochs is over **15 days**.
I think the long training times are due to the high resolution of the videos of kinetics. So, my questions are: 

- did you use a resized version of the dataset (256px on the shorter side)?
- If yes, did you resize the videos using the [script provided](https://mmaction2.readthedocs.io/en/latest/supported_datasets.html#id28) in `mmaction`?

Thank you in advance for your answer

**Comment by xvjiarui** [comment]
Hi @paolomandica 
Sorry for the late reply. 

Yes. I resized the dataset to short side 256. 
I followed [this repo](https://github.com/facebookresearch/video-nonlocal-net/blob/main/DATASET.md) to download the dataset. But the mmaction should also work.
