### ISSUE TITLE
How long does it take to train for 100 epochs?

### ISSUE THREAD

**Issue by pansanity666** [xvjiarui/VFS#2]
Hi, 
May I ask how long does it take to train for 100 epochs and 500epochs on Kinetics, and how many GPUs did you use?

**Comment by xvjiarui** [comment]
Hi @pansanity666 
It depends on your hardware, e.g. GPU, disk. 
I used 2 GPUs for ResNet-18 and 8 GPUs for ResNet-50. 
On RTX3090, ResNet-50 takes 1 week to train 500 epochs. ResNet-18 takes 2 days to train 100 epochs.

**Comment by pansanity666** [comment]
> Hi @pansanity666 It depends on your hardware, e.g. GPU, disk. I used 2 GPUs for ResNet-18 and 8 GPUs for ResNet-50. On RTX3090, ResNet-50 takes 1 week to train 500 epochs. ResNet-18 takes 2 days to train 100 epochs.

Thank you for your reply!

You've solved my question above.  
I have another question about the dataloader for kinetics. You used video dataloader in this repo. Have you ever tried extracting frames from videos first, and than using image dataloder? 
My main concern is that whether the video dataloader will be significantly slower than image dataloder.

Best,

**Comment by xvjiarui** [comment]
I haven't tried since it requires much more disk space. But I think it depends on your disk speed.

**Comment by pansanity666** [comment]
OK, thanks~
