### ISSUE TITLE
Structuring Kinetics400 dataset

### ISSUE THREAD

**Issue by hamidehkerdegari** [xvjiarui/VFS#3]
Hello,

Thanks for sharing your code.
I am trying to replicate your code and followed your instructions in the repo. However, after downloading Kinetics400 dataset, its file structure is quite different from what you suggested for the dataset in the file structure although I followed the link that you have suggested for the dataset downloading. I just wondering if you have any suggestions for that issue?

**Comment by xvjiarui** [comment]
Hi @hamidehkerdegari 
The CV foundation uses different format to organize the dataset. However, you may follow the doc of MMAction to prepare Kinetics 400. 

https://mmaction2.readthedocs.io/en/latest/supported_datasets.html#kinetics-400-600-700

**Comment by hamidehkerdegari** [comment]
Many thanks!
