### ISSUE TITLE
The split txt used for  JHMDB and VIP

### ISSUE THREAD

**Issue by pansanity666** [xvjiarui/VFS#4]
hi, 

May I ask where did you get the split txt file for the evaluation of JHMDB and VIP dataset?
I didn't find these two split file in the [videowalk](https://github.com/ajabri/videowalk) repo.
More concretely, I am confused about the split of validation videos (or you just used  all the videos? ). 
I will be appreciated if you would like to share the code for the evaluation of these two datasets.

best,

**Comment by xvjiarui** [comment]
Hi @pansanity666 
Please find the split txt file for JHMDB [here](https://github.com/Liusifei/UVC/blob/jhmdb/testlist_split1.txt)
The validation list for VIP is `VIP_Fine/lists/val_videos.txt` from your download data.

**Comment by pansanity666** [comment]
> Hi @pansanity666 Please find the split txt file for JHMDB [here](https://github.com/Liusifei/UVC/blob/jhmdb/testlist_split1.txt) The validation list for VIP is `VIP_Fine/lists/val_videos.txt` from your download data.

Thank you for your reply. Problem solved. 
best,

**Comment by pansanity666** [comment]
Hi, I found many kinds of annotations for VIP dataset. Should I use the 'Category_ids' annotation file which is composed of grey annotation masks ?

**Comment by xvjiarui** [comment]
Yes. `Category_id` is the annotation

**Comment by pansanity666** [comment]
> Yes. `Category_id` is the annotation

OK, thank you~
