### ISSUE TITLE
Finding out frame similarity matrix between two video frames

### ISSUE THREAD

**Issue by hamidehkerdegari** [xvjiarui/VFS#6]
Hello,

I was wondering if your code can calculate the frame similarity matrix between two video frames? If yes, which part of your code can do this?Thanks

**Comment by xvjiarui** [comment]
Hi @hamidehkerdegari 
Please find the code here. 
https://github.com/xvjiarui/VFS/blob/master/mmaction/models/trackers/vanilla_tracker.py#L150

**Comment by hamidehkerdegari** [comment]
Thank you @xvjiarui .
